### ISSUE TITLE
Sua badge do Alura Challenge está aqui!

### ISSUE THREAD

**Issue by LucasdeFreitasp** [wildener/aluraflix#1]
Olá, backender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nesse primeiro Challenge de Back-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅
.
Abraços e te vejo nos próximos Challenges!
![Badge AluraFlix reduzido - Sharer](https://user-images.githubusercontent.com/79534537/130669250-b99b06f9-c255-4870-a1f8-94b6063923e8.png)

**Comment by wildener** [comment]
Obrigado, @LucasdeFreitasp!
No momento, estou aprendendo sobre testes no DRF para finalizar o projeto. Minhas ocupações e um período de férias na 3a semana do challenge me impediram de terminar junto aos demais.

Bom... antes tarde do que nunca. Estou gostando da experiência!
